export enum Funcionalidade {
  '' = 0,
  'Consultar pessoa' = 1,
  'Consultar perfil de acesso' = 2,
  'Consultar usuário' = 3,
  'Consultar empresa consultoria' = 4,
  'Consultar cliente' = 5,
  'Consultar funcionário cliente' = 6,
  'Consultar cargo' = 7,
  'Gerenciar pessoa' = 8,
  'Gerenciar perfil de acesso' = 9,
  'Gerenciar usuário' = 10,
  'Gerenciar empresa consultoria' = 11,
  'Gerenciar cliente' = 12,
  'Gerenciar funcionário cliente' = 13,
  'Gerenciar cargo' = 14,
  'Consultar projeto' = 15,
  'Gerenciar projeto' = 16,
}
